### ISSUE TITLE
covariance matrix error

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#21]
<img width="1102" alt="screen shot 2017-07-24 at 1 29 37 pm" src="https://user-images.githubusercontent.com/18297066/28543367-5ed0d47e-7074-11e7-9780-04b37392654b.png">

If I divide by `m` (which is a total flux), the values are not reasonable. However, if I do not divide by `m`, then it gives reasonable values. I think it is related to multiplying multivariate gaussian later, but I am not entirely sure.

**Comment by jennykim1016** [comment]
Fixed!

**Comment by drphilmarshall** [comment]
Very good :-) BTW you can also close issues from within commit messages,
using the magic phrase "fixes #N" or "closes #N" where N is the number of
the issue. This is nice because it allows you to go back and see exactly
what it was you did to fix the problem. You can also use the same phrases
in pull request comments - when the PR is merged, that issue will get
closed.
