### ISSUE TITLE
Unit test: recover moments from a simple input Gaussian

### ISSUE THREAD

**Issue by mbaumer** [jennykim1016/SLRealizer#25]
We have the problem that our multiple ways of computing image moments (manually integrating over the pixels, scipy, etc.) do not give the same results. 
Let's write a unit test that constructs a simple 2D gaussian, computes the moments using the various methods, and use the `assertAlmostEqual(a,b)` method to check that each method's output agrees with the known correct answer.

**Comment by jennykim1016** [comment]
Hi Mike,

I think I solved the bug in the moment_experiment branch (finished unit-testing too and two different methods give correct results!), but I am not able to justify why what I did make sense. Could you help me understand this?

Given a 2d input image, I originally did this (before the bug-fixing):

~~~~
moment_matrix = skimage.measure.moments(image2)

covariance_matrix = [[moment_matrix[0][2], moment_matrix[1][1]], [moment_matrix[1][1], moment_matrix[2][0]]] // the indices look like they are swapped, but those are actually right

// then I generate multivariate gaussian with computed moments
rv = scipy.stats.multivariate_normal([first_moment_x,first_moment_y], covariance_matrix, allow_singular=True)

// scale it and add it to the new image array
image_new = image_new + rv.pdf(pos)*zeroth_moment
~~~~

This was 10,000 times off both in the size and the brightness. The bug was caused because the volume of the returned 2d gaussian curve is not one(1) but rather 10,000. Thus, in order to get right values, I had to change the code as follows:

~~~~
moment_matrix = skimage.measure.moments(image2)

covariance_matrix = [[moment_matrix[0][2], moment_matrix[1][1]], [moment_matrix[1][1], moment_matrix[2][0]]] // the indices look like they are swapped, but those are actually right

*** // here I had to divide covariance_matrix by 10,000
covariance_matrix = covariance_matrix / 10000 *** (1) 

// then I generate multivariate gaussian with computed moments
rv = scipy.stats.multivariate_normal([first_moment_x,first_moment_y], covariance_matrix, allow_singular=True)

// scale it and add it to the new image array
*** image_new = image_new + rv.pdf(pos)*zeroth_moment / 10000 *** (2)
~~~~

then this gives me right values. I think dividing the returned gaussian with 10000 make sense (2) , but I am not sure why we have to divide covariance_matrix by 10000 (1). First moments do not have to be divided by 10000 to get right values. I think I am missing some important pieces to answer the question; how should I justify the division of covariance_matrix with this pseudo-magic number?

Thank you so much in advance for your help!

**Comment by mbaumer** [comment]
Hi Jenny,
It looks like you fixed this in your most recent PR, but let me know if
this is still giving you trouble.
Mike

**Comment by jennykim1016** [comment]
Hi mike,

I solved the problem, but I think I am still confused of some properties of multivariate gaussians. I will try to read and study more, and if I still can't get it, I will ask you tomorrow in person. Thank you so much!
