### ISSUE TITLE
Zeropoint should be changed

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#29]
I just set the zeropoint to be 3, but to be exact, I have to change the zeropoint -- the value should be same as OM10's.

**Comment by drphilmarshall** [comment]
There is a natural zeropoint to use. If we define the units of flux to be
"AB nanomaggies" (nmgy), then the relationship between AB magnitude m and
flux f is

m = -2.5 log_10 ( f / 10^9 nmgy) = 22.5 - 2.5 log_10 ( f / nmgy )

because a source with flux 1 AB maggie has apparent magnitude zero. The AB
nanomaggie is a sensible flux unit for extragalactic sources.

If you assert a zeropoint of 22.5, then when you convert AB magnitudes to
flux you will get flux in units of AB nanomaggies. Note that photometric
calibration is about setting the zeropoint which is equivalent to choosing
the units of flux. In our toy case, all the magnitudes are calibrated to
the AB system, so we can just choose nmgy as our flux unit.
