### ISSUE TITLE
Action Items for this week - still adding

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#48]
- [x] put galsim options to calculate the moments
- [x] **ADD NOISE TO GALSIM DATA - THOSE ARE NOISE FREE**
- [x] unit test galsim moments
- [x] Draw cornerplots with galsim object catalog
_did it for 30*50 sample, need to do with a bigger sample_
- [x] overlay SDSS data
- [x] merge `extract_corner` into one
- [ ] noise gives weird error
 => this wasn't because of noise. It was because of ellipticity #49 
- [x] didn't use few values in SDSS while generating the cornerplot

**Comment by mbaumer** [comment]
Hi Jenny, just a couple notes on Galsim features that might make these steps easier (you may already be using these)

1. The obs_hist gives us the size of the PSF during each observation. We can construct a psf using Galsim, convolve it with the sources we've constructed, and then measure shapes of these psf-convolved objects. This is actually pretty close to what happens in reality! The code to do this would look like:
```python
#normal realization code here
realization = lens_galaxy + src_img1 + src_img2 ...
psf = galsim.Gaussian(flux=1, sigma=psf_sigma_from_obshist) #psf flux always should be 1.
final = realization.Convolve([realization,psf]) #convolve the "perfect" realization with the PSF
```

2. In addition, rather than adding noise to the catalog quantities manually (according to the toy model we made up with Phil), galsim can easily add noise directly to the images. We can use the sky background value from the obshist to set the noise correctly. The code would be like:
```python
#realization + psf convolution code here
random_number_generator = galsim.BaseDeviate(random_seed) #random seed can be any number you want
noise = galsim.PoissonNoise(rng, sky_level=sky_level_from_obshist)
noisy_psf_convolved_image = psf_convolved_image.addNoise(noise)
```

We can save step 2 for later if you want (since we'll have to figure out how galsim returns the shape and position errors), but step 1 should make things easier for you!

For examples of other galsim features, check out the demos: https://github.com/GalSim-developers/GalSim/wiki/Tutorials

**Comment by jennykim1016** [comment]
~ Decide to add noise manually. Closing the issue~
